version: '2'

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:3'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - 'zookeeper_data:/bitnami/zookeeper'
  kafka-server:
    image: 'bitnami/kafka:2'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    volumes:
      - 'kafka_data:/bitnami/kafka'
    depends_on:
      - zookeeper-server
  cassandra-db:
    container_name: cassandra
    image: 'bitnami/cassandra:3'
    ports:
      - '9042:9042'
    environment:
      - CASSANDRA_SEEDS=cassandra-db
      - CASSANDRA_PASSWORD_SEEDER=yes
      - CASSANDRA_USER=cassandra
      - CASSANDRA_PASSWORD=cassandra

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  cassandra_data:
    driver: local