/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package thriftGenerated;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.13.0)", date = "2020-09-19")
public enum Room implements org.apache.thrift.TEnum {
  KITCHEN(0),
  BEDROOM(1),
  LIVING_ROOM(2),
  BATHROOM(3);

  private final int value;

  private Room(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   *
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static Room findByValue(int value) {
    switch (value) {
      case 0:
        return KITCHEN;
      case 1:
        return BEDROOM;
      case 2:
        return LIVING_ROOM;
      case 3:
        return BATHROOM;
      default:
        return null;
    }
  }

  @Override
  public String toString() {
    switch (value) {
      case 0:
        return "Kitchen";
      case 1:
        return "Bedroom";
      case 2:
        return "Living Room";
      case 3:
        return "Bathroom";
      default:
        return null;
    }
  }
}
